### ISSUE TITLE
小程序调试没有问题，但是小程序发布出来显示空白页

### ISSUE THREAD

**Issue by woshihehao** [walcer/TianguoguoXiaopu#32]
微信小程序的开发者官方运维中心提示错误Error: module "dist/packages/@zanui/noticebar/index" is not defined
Error: module "dist/packages/@zanui/noticebar/index" is not defined
at require (WASubContext.js:1:1358875)
at WASubContext.js:1:1358626
at https://dist/packages/@zanui/index.js:4:21
at https://usr/app-service.js:7720:10

**Comment by woshihehao** [comment]
微信：13438866076。大佬可以加一下我，我把错误图片和本地调试成功视频发给你看一下。
