### ISSUE TITLE
我本地测试是正常的，但是上传代码出错

### ISSUE THREAD

**Issue by shen9naxier** [walcer/TianguoguoXiaopu#36]
Error: module "dist/packages/@zanui/noticebar/index" is not defined 
at require (WASubContext.js:1:1400926)
at (WASubContext.js:1:1400675)
at (app-service.js:7806:170)
at require (WASubContext.js:1:1401059)
at global code (app-service.js:7807:17)
at (native code)
at value (WAService.js:1:111950)
at (WAService.js:1:113661)
at (WAService.js:1:109422)
at (WAService.js:1:119886)
at (WAService.js:1:118870)
at forEach (native code)
at (WAService.js:1:118834)
at (WAService.js:1:119886)
at m (WAService.js:1:1908)
global code

**Comment by kuzu008** [comment]
我跟你一样的错误，请问你解决了么？

**Comment by shen9naxier** [comment]
> 我跟你一样的错误，请问你解决了么？

好久了，不太记得。应该是删除dist/packages/@zanui/noticebar下的index.json文件就好了。你可以试一下
